#!/bin/csh -f

# ============================================ #
#	ModelSim Lincence Setup
# ============================================ #
setenv LM_LICENSE_FILE 1717@earth

# ============================================ #
#	ModelSim Environment Setup
# ============================================ #
setenv MTI_HOME /cadtools/modelsim6.5b/modeltech/
set path = ( $path $MTI_HOME/bin )

# ============================================ #
#	USER DEFINE PATH
# ============================================ #
setenv SIMTMPDIR galileo_founder
#setenv SIMTMPDIR test

# ============================================ #
#	ModelSim compile path Setup
# ============================================ #
#setenv WORK /tmp/$USER/$SIMTMPDIR/work
#setenv SIMLINK simlink
#setenv LIBLINK liblink
#
#if ( ! -d /tmp/$USER ) then
#	mkdir /tmp/$USER
#endif
#
#if ( ! -d /tmp/$USER/$SIMTMPDIR ) then
#	mkdir /tmp/$USER/$SIMTMPDIR
#endif
#
#if ( ! -d $WORK ) then
#	mkdir $WORK
#endif
#
#if ( ! -f $WORK/_info ) then
#	vlib $WORK
#	vmap work $WORK
#endif
#
# ============================================ #
#	PSC Plain Code Sim Environment
# ============================================ #
#setenv GALILEO_PSC_DIR `pwd`/psclink_plain	

# ============================================ #
#	Simulation Script
# ============================================ #
#compile
vlog 								\
#	-work $WORK 						\
	-timescale 1ps/1ps				\
	+nocheckALL						\
	+notimingcheck					\
	+delayed_timing_cheks			\
#	-fast							\
	-timescale 1ps/1ps				\
	+define+PLL_resolution_1ps		\
	+incdir+.						\
	+libext+.v+.vp					\
	+define+IBM_RTL_WRAPPER			\
	+define+GALILEO_CHIP			\
	-nodebug						\
#	-O1								\
#	-y ./liblink/STANDARD_LIB/ibm_cu08/v7.0fix/verilog	\
#	-y ./liblink/STANDARD_LIB/ibm_cu08/v7.0/verilog		\
#	-y ./liblink/CUSTOM_LIB/verilog						\
#	-y ./liblink/CUSTOM_LIB/verilog_wrapper				\
#	-file ./simlink/sim_plain.tree		\
#	-file ./simlink/sim_founder_enc.tree		\
	-R								\
#	+no_notifier					\
#	+nocheckALL 					\
#	+notimingchecks 					\
#	-t 1ps							\
#	-voptargs=+acc=rn+/TOTAL_TEST/GALILEO_WRAPPER/GALILEO/GCORE			\
#	-voptargs=+acc=rn+ibm_memory_bist_generic		\
#	-voptargs=+acc=rn+ibm_memory_dram_generic 		\
#	-voptargs=+acc=rn+ibm_memory_farr_generic		\
#	-voptargs=+acc=rn+ibm_memory_rf2_generic		\
#	-voptargs=+acc=rn+ibm_memory_sram1_generic		\
#	-voptargs=+acc=rn+ibm_memory_sram1fh_generic	\
#	-voptargs=+acc=rn+ibm_memory_sram2_generic		\
#	-voptargs=+acc=rn+ibm_memory_sram2fh_generic	\
#	-voptargs=+acc=rn+ibm_memory_sram4ptr_generic	\
#	-voptargs=+acc=rn+ibm_memory_sram4ptr_generic	\
#	+delayed_timing_cheks			\
#	-capacity						\
#	-c
#-R : Run Option 
#-c : Run time, Non GUI Option 


#if ($1 == "gui") then
##gui mode
	vsim							\
	-voptargs=+acc					\
#	test_top 
#else
#batch mode
#	vsim							\
	-c 								\
#	-voptargs=+acc					\
#	TOTAL_TEST 
#endif
